#spring.r2dbc.url=r2dbc:mysql://[아이디]:[비밀번호]@[호스트]:[port]/[database]
spring.r2dbc.url: r2dbc:h2:mem://localhost/~/workspace/study/blog/spring-data-r2dbc/doc/h2/r2dbc?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
logging.level.org.springframework.data.r2dbc: DEBUG
